### ISSUE TITLE
Первое Ревью

### ISSUE THREAD

**Issue by Hanqnero** [keksmd/lab4#1]
- Названия пакетов не по [стандарту оракл](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).
- Добавить UML в README.MD, чтобы ее было видно на странице репозитория.
- Типы `AlivePerson` и `DeadPerson`. Жив человек или нет это не свойство объекта?
- `Main.java: 48-60` Можно заменить на статический метод `valueOf(String s)`:
```
switch (line) {
                case "утро":
                    StoryTell.setTime(Time.MORNING);
                    break;
                case "день":
                    StoryTell.setTime(Time.DAY);
                    break;
                case "вечер":
                    StoryTell.setTime(Time.EVENING);
                    break;
                case "ночь":
                    StoryTell.setTime(Time.NIGHT);
                    break;
```
-  "Бумажные" мысли в `Thoughts.java`

**Comment by keksmd** [comment]
У живых и мертвых людей,очевидно должны быть разные методы, поэтому и классы для их реализации разные

**Comment by keksmd** [comment]
Поправил код:

-  `Main.java: 48-60` теперь выглядит так

```
            Boolean flag = false;
            for(Time t:Time.values()){
                if(t.getValue().equals(line)){
                    StoryTell.setTime(t);
                    flag = true;
                }
            }
            if(!flag){
                try {
                    throw new IOException();
                } catch (IOException e) {
                    System.out.println("Вы ввели неправильное время, попробуйте еще раз");
                    startTime();
                }
            }

```

- Переместил всё в package `ru.alexkekiy`

-  Добавил UML - `diag.puml` в репозиторий

-   объекты `Thoughts`  теперь имеют `private boolean positive`, который отвечает за позитивность мысли, и в методах `think(Thoughts t)` ,`remember(Person p,Thoughts t)` появился вот такой кусочек

```
if(!t.isPositive()){`
            this.setStamina(Math.max(this.getStamina()-3,0));
        }else{
            this.setStamina(Math.min(this.getStamina()+3,100));
        }
```
 который уменьшает stamina если мысль была негативной и увеличивает,если она была позитивной
