### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Strok1n** [keksmd/lab4#3]
Reviewer contact: https://t.me/strok1n

1. Чтобы код стал более читабельным, методы и поля классов items.Item, items.Food (и всех остальных классов) нужно передвинуть так, чтобы эти классы соответствовали шаблону: 
![image](https://github.com/keksmd/lab4/assets/148381112/67698db2-6b85-4dd8-b878-72975d854784)
2. В классе ownable.locations.abstracts.classes.Loc переименовать поле usl, так, чтобы название поля соответствовало смыслу этого поля. Это очень повысит читабельность кода. Иначе трудно понять, зачем эта переменная нужна.
3. В классе utilities.CreatePerson нужно передавать StoryTell в качестве параметра, иначе данный код сильно привязывает класс CreatePerson к классу Main.
![image](https://github.com/keksmd/lab4/assets/148381112/73b5fb9d-c848-4aaf-8627-f57bd574ef89)
4. В пакете ownable.persons.real.classes в классах Luis, Jude, DeadGaje есть конструкторы, принимающие имя и пол, но зачем нужны эти конструкторы, мы же не собираемся создавать Луиса женского пола или с каким-то другим именем. Нужно создать конструктор без параметров, который явно передаёт в конструктор super имя и пол соответствующего персонажа.
5. В пакете exeptions (you mean exceptions, right) классы Checked, Unchecked и FileException не очень хорошо названы. По их названиям неясно что это за исключения и где они используются. Следует назвать эти классы более подробным описанием.

**Comment by keksmd** [comment]
Залил исправленный код
